version: "2"
services:
  jaeger:
    image: jaegertracing/all-in-one:0.8.0
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - jaeger-example

  front-end:
    image: "alfredodeza/micro-frontend"
    ports:
      - "5000:5000"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - jaeger-example
    depends_on:
      - jaeger

  back-end:
    image: "alfredodeza/micro-backend"
    ports:
      - "5001:5000"
    networks:
      - jaeger-example
    depends_on:
      - jaeger

networks:
  jaeger-example:
